In [ ]:
import numpy as np
import sklearn

## neural network

In [2]:
class neuralNetwork:
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # initialise the input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # set weights
        self.weight_layer1 = np.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.weight_layer2 = np.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))

        # learning rate
        self.lr = learningrate
        
        # activation function: sigmoid function
        self.activation_function = lambda x: 1 / (1 + np.exp(-x))
        
        
    
    # train the neural network
    def train(self, input_data, target_data):
        # Forward propagation
        # convert inputs list to 2D array
        inputs = np.array(input_data, ndmin=2).T
        targets = np.array(target_data, ndmin=2).T
        
        # calculate hidden layer
        hidden_input = np.dot(self.weight_layer1, inputs)
        hidden_output = self.activation_function(hidden_input)
        
        # calculate final output layer
        final_input = np.dot(self.weight_layer2, hidden_output)
        final_output = self.activation_function(final_input)
        
        # output layer error: (target - actual)
        output_error = targets - final_output
        # hidden layer error is the output_error, split by weights, recombined at hidden nodes
        hidden_error = np.dot(self.weight_layer2.T, output_error) 
        
        # Backward propagation
        
        # update the weights first between the hidden and output layers
        self.weight_layer2 += self.lr * np.dot((output_error * final_output * (1.0 - final_output)), np.transpose(hidden_output))
        
        # update the weights between the input and hidden layers
        self.weight_layer1 += self.lr * np.dot((hidden_error * hidden_output * (1.0 - hidden_output)), np.transpose(inputs))
        
    
    # predict the neural network
    def predict(self, inputs_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T
        
        # calculate hidden layer
        hidden_input = np.dot(self.weight_layer1, inputs)
        hidden_output = self.activation_function(hidden_input)
        
        # calculate final output layer
        final_input = np.dot(self.weight_layer2, hidden_output)
        final_output = self.activation_function(final_input)
        
        return final_output

In [3]:
# number of input, hidden and output nodes
input_nodes = 2
hidden_nodes = 3
output_nodes = 1

# learning rate is 0.2
learning_rate = 0.2

# instantiate neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

In [4]:
# test
n.predict([1.0, 0.5])

array([[0.54606999]])

## Generate Test Data
Two inputs.
If a > b, output = 1

In [5]:
X = np.random.rand(1000, 2)
y = (X[:, 0] > X[:, 1]).astype(int)

In [6]:
X[:2]

array([[0.34435401, 0.51957542],
       [0.40619781, 0.96634599]])

In [7]:
y[:2]

array([0, 0])

## Train data from 0-800 and re-train it 100 times

In [8]:
for j in range(100):
    for i in range(800):
        n.train(X[i], y[i])

## Test
Get y_pred from rest 200 data

In [9]:
y_pred = []

In [10]:
for i in range(800, 1000):
    y_pred.append(n.predict(X[i]).item())

In [11]:
import sklearn.metrics

In [12]:
sklearn.metrics.mean_squared_error(y[800:1000], y_pred)

0.004968872986976181

### Sample output logs

In [13]:
y_pred[:10]

[0.999045198912345,
 0.9997112516191257,
 0.999897845291202,
 0.05409676217306056,
 0.9997343741269037,
 0.9998962334927916,
 5.199879701695559e-05,
 0.9994893913574738,
 0.9998295123983078,
 0.9998803424278838]

In [14]:
y[800:810]

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1])